#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "smart_todo"

if ENV["ENABLE_SMART_TODO"] && !ARGV.include?("--dispatcher")
  ARGV << "--dispatcher" << "slack"
end

exit SmartTodo::CLI.new.run
