#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'smart_todo'

unless ENV['ENABLE_SMART_TODO']
  puts 'Not running SmartTodo since the ENABLE_SMART_TODO ENV is not set'

  exit(0)
end

SmartTodo::CLI.new.run
